### ISSUE TITLE
Xamarin Android - Set "On" state programmatically? Is this possible?

### ISSUE THREAD

**Issue by Rhonage** [ebanx/swipe-button#29]
Hey there.

I'm using your awesome button to enable a long running Android Service. When the user returns to the application I need to retain the "on" state for the button.

I can't seem to find a way to do this. Any suggestions?

Cheers

**Comment by Rhonage** [comment]
Sorry, brainfart. I'm able to do this by calling the IOnStateChangeListener method OnStateChanged(), and passing it a "true" argument.

**Comment by Rhonage** [comment]
Note that the .NET Nuget package does not allow me to use the "toggleState()" method.

**Comment by Rhonage** [comment]
Also, same question but for setting text programmatically.

**Comment by leandroBorgesFerreira** [comment]
#30

**Comment by leandroBorgesFerreira** [comment]
@Rhonage you can use setText() to change test programatically.
