### ISSUE TITLE
add some useful function

### ISSUE THREAD

**Issue by bkhezry** [ebanx/swipe-button#4]
Hi, thanks for this library.
please add some function for changing start state of swipe-button from enabling icon to disabling icon. now it is disabled by default.
also change value of `button_background`, `inner_text_background` and etc programmatically.

**Comment by leandroBorgesFerreira** [comment]
Hi bkhezry. Thanks for the hint. 

I try to do that tomorrow or next week.

**Comment by ikermart** [comment]
Is it possible to change swipe button text programatically? I can not access to public method, .setText()

**Comment by leandroBorgesFerreira** [comment]
No Ikermart, not yet. You will implement those requests in the next week.

**Comment by leandroBorgesFerreira** [comment]
Hi folks. Now it is possible to change the button parameters programmatically. You can also set the initial state of the button as enabled. Now use the 0.5.0 version.

**Comment by bkhezry** [comment]
Hi @leandroBorgesFerreira, there is a bug in this version. the wrong icon showing in the lock and unlock state.

**Comment by leandroBorgesFerreira** [comment]
Hello, bkhezry. Thanks for you contribution. This bug is fixed now in the version 0.5.1
