### ISSUE TITLE
change state with click on right side of the button

### ISSUE THREAD

**Issue by bkhezry** [ebanx/swipe-button#7]
When clicking on right side of the button, state will be changed without the need to swipe.

**Comment by leandroBorgesFerreira** [comment]
Hi bkhezry. Based on your pull request I will make second version of the button, for a custom toggle button. I don't see adding this behavior in the current button as a good idea because it is better to the button to have only one responsability

**Comment by bkhezry** [comment]
This issue didn't relative to my PR. Library has this bug. When you click right side of button and without swipe button, the state of it will be changing.

**Comment by leandroBorgesFerreira** [comment]
@bkhezry  Fixed in version 0.5.2
