### ISSUE TITLE
How to Activate by Code

### ISSUE THREAD

**Issue by TidaBlabla** [ebanx/swipe-button#9]
How can I switch from lock/unlock by code. I have the possible to request by isActive(boolean) but not set by setActive(boolean).

setActivated(boolean) seems not work for that purpose.

**Comment by leandroBorgesFerreira** [comment]
Hi, TidaBlaBla. I will take a look at your problem at Monday.

**Comment by leandroBorgesFerreira** [comment]
@TidaBlabla You can use the toggleState() method. 

Something like this: 

```
if (!swipeButton.isActive()) {
        swipeButton.toggleState();
}
```

**Comment by leandroBorgesFerreira** [comment]
@TidaBlabla Did this solution worked for you?

**Comment by leandroBorgesFerreira** [comment]
I am closing this problem as it is not active for a while and I believe the code provided can solve you problem. Feel free to reopen it if needed.
